// Editorial content is rendered as static HTML so lessons remain readable without JavaScript.
export const reviewedOn = '2026-09-14';
export const courses = [
  {
    slug: 'valeurs-republique',
    title: 'Liberté, égalité, fraternité et laïcité : comprendre les principes',
    shortTitle: 'Principes et valeurs',
    description: 'Distinguer les libertés individuelles, l’égalité de traitement et la neutralité des services publics à partir de situations expliquées.',
    objective: 'Savoir identifier la valeur en jeu sans confondre la règle applicable à un agent public et celle applicable à un usager.',
    sections: [
      ['liberte', 'La liberté suppose aussi des limites', `<p>La liberté permet de choisir ses idées, ses convictions et de les exprimer. Elle ne donne pas le droit de porter atteinte aux autres. La Déclaration de 1789 relie ainsi l’exercice d’une liberté au respect de celle d’autrui. Pour comprendre une situation, cherchez ce que fait réellement la personne : exprime-t-elle un désaccord, menace-t-elle quelqu’un ou empêche-t-elle une autre personne d’exercer un droit ? Ces actions ne sont pas équivalentes.</p><p>Exemple pédagogique : deux voisins ne partagent pas les mêmes opinions. Ils peuvent discuter et critiquer des idées. Le désaccord ne justifie ni les violences ni les menaces. Dans un QCM, une proposition qui autorise tout au nom de la liberté oublie donc une partie de la règle. À l’inverse, interdire toute divergence d’opinion supprimerait cette liberté.</p>`],
      ['egalite', 'Égalité et fraternité : deux idées complémentaires', `<p>L’égalité devant la loi s’oppose aux privilèges attachés à la naissance ou à l’origine. Elle ne signifie pas que toutes les personnes ont les mêmes revenus ou les mêmes besoins. Une aide attribuée selon des critères légaux de ressources n’est pas, par sa seule existence, contraire à l’égalité. Il faut distinguer un critère pertinent prévu par les règles et une préférence arbitraire.</p><p>La fraternité invite à considérer les autres comme des membres de la même communauté humaine. Dans notre exemple, aider un voisin à comprendre un courrier peut illustrer la solidarité. Cela ne remplace pas les droits garantis par les institutions : une personne ne doit pas dépendre uniquement de la bonne volonté d’un voisin pour être traitée équitablement.</p>`],
      ['laicite', 'La laïcité protège la liberté de conscience', `<p>La laïcité garantit la possibilité de croire, de ne pas croire et de changer de conviction. L’État doit rester neutre à l’égard des religions. Un agent public, pendant son service, est soumis à une obligation de neutralité. Il ne doit pas faire dépendre l’accueil d’un usager de sa religion.</p><p>L’usager d’un service public n’est pas soumis à la même obligation générale de neutralité que l’agent. Il conserve sa liberté de conscience, dans le respect du fonctionnement du service et des règles applicables. Des règles particulières existent, notamment dans les écoles publiques pour les élèves. Évitez donc les affirmations absolues telles que « toute expression religieuse est interdite partout ».</p>`],
    ],
    questions: [
      ['Un agent de mairie reçoit deux personnes de convictions différentes. Quelle attitude est adaptée ?', ['Accorder la priorité à sa propre religion.', 'Appliquer les mêmes règles d’accueil.', 'Demander aux deux personnes de changer de conviction.', 'Refuser tout dossier qui mentionne une religion.'], 1, ['La préférence religieuse contredit la neutralité du service.', 'La neutralité protège un traitement égal, indépendamment des convictions.', 'L’agent ne peut imposer une croyance aux usagers.', 'Une conviction ne justifie pas, à elle seule, un refus de service.']],
      ['Deux personnes ne partagent pas la même opinion politique. Que permet la liberté d’expression ?', ['Menacer l’autre pour obtenir son accord.', 'Interdire toutes les opinions différentes.', 'Débattre dans le respect des limites légales.', 'Exiger que l’administration adopte leur opinion.'], 2, ['Une menace ne devient pas licite parce qu’elle accompagne une opinion.', 'La liberté protège aussi le désaccord.', 'On distingue la discussion des comportements portant atteinte aux droits d’autrui.', 'L’expression individuelle ne commande pas les décisions administratives.']],
      ['Quelle phrase décrit le mieux la laïcité ?', ['Chacun doit choisir une religion.', 'Les agents publics choisissent quels croyants aider.', 'Aucune personne ne peut avoir de conviction.', 'La liberté de conscience est garantie et l’État est neutre.'], 3, ['La liberté de ne pas croire est également protégée.', 'Le service public ne privilégie pas une religion.', 'La laïcité ne supprime pas les convictions personnelles.', 'Cette réponse associe la liberté des personnes et la neutralité publique.']],
    ],
    exercise: 'Inventez deux scènes au guichet d’une mairie : une avec un agent, l’autre avec un usager. Pour chacune, nommez la personne, la règle applicable et le comportement attendu. Cette précision évite de réciter une règle trop générale.',
    sources: [
      ['Laïcité : définition et liberté de conscience', 'https://www.laicite.gouv.fr/quest-ce-que-laicite'],
      ['Obligations de neutralité des agents publics', 'https://www.fonction-publique.gouv.fr/etre-agent-public/mes-droits-et-obligations/laicite-et-neutralite-de-la-fonction-publique'],
      ['Déclaration de 1789, notamment articles 1, 4 et 10', 'https://www.legifrance.gouv.fr/contenu/menu/droit-national-en-vigueur/constitution/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789'],
    ],
  },
  {
    slug: 'institutions',
    title: 'Institutions françaises : qui décide, qui vote et qui contrôle ?',
    shortTitle: 'Institutions et politique',
    description: 'Une méthode pour distinguer les missions du Parlement, du Gouvernement et des institutions, avec trois QCM entièrement expliqués.',
    objective: 'Associer une action à l’institution compétente, au lieu de mémoriser seulement des noms de responsables.',
    sections: [
      ['roles', 'Commencer par les verbes', `<p>Les institutions se comprennent mieux à partir de leurs missions. Le Parlement vote les lois et contrôle l’action du Gouvernement. Le Gouvernement conduit la politique de la Nation. Le Premier ministre dirige son action. Le président de la République veille au respect de la Constitution et nomme le Premier ministre. Ces fonctions se complètent, mais ne sont pas interchangeables.</p><p>La bonne question de révision est donc « qui fait quoi ? ». Pour chaque mot rencontré, écrivez un verbe : voter, diriger, nommer, contrôler. Si vous avez appris uniquement le nom d’une personnalité, vous risquez de vous tromper lorsque la question porte sur la fonction ou lorsqu’un responsable change.</p>`],
      ['parlement', 'Deux assemblées composent le Parlement', `<p>Le Parlement français réunit l’Assemblée nationale et le Sénat. Les députés siègent à l’Assemblée nationale ; les sénateurs au Sénat. Un ministre appartient au Gouvernement : son titre ne désigne pas un membre de l’une de ces deux assemblées. Le mot « Parlement » ne signifie donc pas « réunion des ministres ».</p><p>Le travail sur une loi peut faire intervenir le Gouvernement et les parlementaires. Le fait qu’un ministre présente un projet ne signifie pas qu’il vote seul la loi. Pour un exercice d’introduction, distinguez l’initiative d’un texte, son examen et son adoption. Ne transformez pas cette explication en règle selon laquelle chaque texte suit exactement le même chemin : la Constitution prévoit différentes procédures.</p>`],
      ['constitution', 'La Constitution organise les pouvoirs', `<p>Une Constitution fixe les règles fondamentales d’organisation de l’État. La Constitution actuelle de la Ve République date de 1958. Les lois doivent respecter les normes constitutionnelles. Le Conseil constitutionnel intervient notamment dans ce contrôle. Une majorité politique ne dispose donc pas d’un pouvoir sans limites.</p><p>Exemple pédagogique : dans une discussion, quelqu’un affirme que gagner une élection permet d’ignorer tous les droits fondamentaux. Pour analyser cette proposition, séparez la légitimité électorale et les règles qui encadrent l’exercice du pouvoir. Être élu donne une fonction ; cela ne supprime pas la Constitution. La protection des droits est précisément l’un des enjeux de ces limites.</p>`],
    ],
    questions: [
      ['Quelles institutions composent le Parlement français ?', ['Le Gouvernement et les préfectures.', 'L’Assemblée nationale et le Sénat.', 'Le président et les maires.', 'Les tribunaux et les ministères.'], 1, ['Ces organismes ne sont pas les deux chambres du Parlement.', 'Les deux chambres sont l’Assemblée nationale et le Sénat.', 'Le président et les élus municipaux ont d’autres fonctions.', 'Cette réponse mélange justice et administration.']],
      ['Un exercice demande qui vote la loi en France. Quelle réponse désigne l’institution attendue ?', ['Le Parlement.', 'Chaque maire séparément.', 'Les seuls membres du Gouvernement.', 'Une entreprise privée.'], 0, ['Voter la loi est une mission du Parlement.', 'Les décisions municipales ne remplacent pas la loi nationale.', 'Le Gouvernement peut proposer des textes, mais cela ne revient pas à voter seul les lois.', 'Une entreprise n’exerce pas le pouvoir législatif.']],
      ['Pourquoi la Constitution est-elle importante même après une élection ?', ['Elle remplace le choix des électeurs.', 'Elle change automatiquement chaque semaine.', 'Elle encadre l’exercice des pouvoirs publics.', 'Elle ne concerne que les visiteurs étrangers.'], 2, ['L’existence de règles constitutionnelles ne supprime pas les élections.', 'Une révision obéit à une procédure, pas à un rythme automatique.', 'L’exercice du pouvoir reste soumis à des règles fondamentales.', 'Elle organise les institutions de la République dans leur ensemble.']],
    ],
    exercise: 'Tracez trois colonnes sur une feuille : institution, membres, mission. Placez Assemblée nationale, Sénat et Gouvernement. Puis expliquez pourquoi présenter un projet de loi et voter une loi ne désignent pas la même action. En cas d’hésitation, revenez au verbe avant de choisir une réponse.',
    sources: [
      ['Vie publique : définir le Parlement', 'https://www.vie-publique.fr/fiches/19485-comment-definir-le-parlement'],
      ['Constitution de 1958 : articles 5, 8, 20, 21 et 24', 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000571356/'],
      ['Vie publique : protection des droits des citoyens', 'https://www.vie-publique.fr/fiches/23868-comment-sont-proteges-les-droits-des-citoyens'],
    ],
  },
  {
    slug: 'droits-devoirs',
    title: 'Droits et devoirs : reconnaître une discrimination et raisonner avec la loi',
    shortTitle: 'Droits et devoirs',
    description: 'Comprendre la discrimination, les recours et les obligations communes grâce à des exemples et des réponses commentées.',
    objective: 'Distinguer une différence de traitement justifiée d’un critère interdit et choisir une réaction qui protège les droits.',
    sections: [
      ['discrimination', 'Repérer le motif d’un refus', `<p>Une discrimination peut intervenir dans l’accès à un emploi, à un logement ou à un service. Pour l’identifier, ne regardez pas seulement le résultat : cherchez le motif du traitement différent. L’origine, le sexe ou le handicap font notamment partie des critères protégés. Un refus reposant sur un critère interdit n’est pas une simple préférence personnelle sans conséquence.</p><p>Toute différence n’est cependant pas automatiquement une discrimination illégale. Certaines distinctions sont prévues par la loi ou répondent à des conditions encadrées. Dans un QCM, lisez précisément le critère indiqué. Notre exemple d’un recrutement suppose que les candidats satisfont aux exigences du poste : le problème vient alors d’un rejet fondé uniquement sur leur origine, et non d’une qualification manquante.</p>`],
      ['recours', 'Réagir sans se faire justice soi-même', `<p>Une personne qui pense subir une discrimination peut conserver les éléments utiles, demander conseil et saisir le Défenseur des droits. Une plainte est également possible. Le choix du recours dépend des faits. La protection des droits passe par des démarches et des institutions, pas par des représailles.</p><p>Pour réviser, comparez deux réponses : « conserver le message de refus et rechercher une aide » et « menacer l’auteur ». La première permet de documenter les faits ; la seconde ajoute un comportement dangereux et ne résout pas juridiquement le problème. Les situations pédagogiques ci-dessous servent à reconnaître ce raisonnement, sans remplacer l’examen d’un dossier réel.</p>`],
      ['obligations', 'Les droits s’accompagnent de règles communes', `<p>Vivre en société implique de respecter la loi et les droits d’autrui. Une règle ne devient pas facultative parce qu’on la trouve désagréable. On peut la contester par les voies prévues, participer au débat ou défendre une évolution, mais le désaccord ne crée pas à lui seul une autorisation de nuire.</p><p>La Déclaration de 1789 présente aussi la contribution commune aux dépenses publiques, répartie selon les capacités. Cela aide à distinguer égalité et montant identique pour tous. Dans une question sur l’impôt, évitez deux raccourcis : croire que chacun choisit librement s’il contribue, ou croire que l’égalité impose une somme uniforme indépendamment des règles fiscales.</p>`],
    ],
    questions: [
      ['Deux candidats remplissent les conditions d’un poste. L’un est refusé uniquement en raison de son origine. Quel problème apparaît ?', ['Une règle normale de politesse.', 'Une discrimination.', 'Une obligation imposée à tous les employeurs.', 'Une différence sans rapport avec les droits.'], 1, ['Le motif du refus concerne l’égalité de traitement, pas la politesse.', 'L’origine est un critère protégé : elle ne justifie pas ici le rejet.', 'Aucune obligation générale ne prescrit un tel rejet.', 'Le recrutement fait partie des domaines où la discrimination est encadrée.']],
      ['Quelle réaction est adaptée face à un refus que l’on pense discriminatoire ?', ['Détruire tous les messages.', 'Menacer la personne.', 'Conserver les éléments et contacter un organisme compétent.', 'Renoncer nécessairement à tout recours.'], 2, ['Les éléments conservés peuvent aider à établir les faits.', 'La menace ne protège pas les droits et peut constituer une infraction.', 'Documenter les faits et demander une aide permet d’identifier les démarches possibles.', 'Il existe des recours ; le refus initial ne les supprime pas.']],
      ['Une personne désapprouve une règle. Quelle affirmation est la plus juste ?', ['Elle peut chercher à la faire évoluer par les voies légales.', 'Elle peut menacer ceux qui l’appliquent.', 'Elle est automatiquement dispensée de la respecter.', 'Elle perd immédiatement tous ses droits.'], 0, ['Le débat et les recours permettent une contestation dans un cadre légal.', 'Le désaccord n’autorise pas les menaces.', 'Une opinion personnelle n’accorde pas une dispense.', 'Exprimer un désaccord ne fait pas disparaître les droits fondamentaux.']],
    ],
    exercise: 'Dans une situation de refus, soulignez trois éléments : le domaine concerné, le motif donné et la réaction proposée. Une réponse peut sembler empathique tout en recommandant une action inadaptée. Vérifiez toujours les trois éléments avant de choisir.',
    sources: [
      ['Service Public : discrimination et démarches', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F19448'],
      ['Déclaration de 1789 : libertés et contribution commune', 'https://www.legifrance.gouv.fr/contenu/menu/droit-national-en-vigueur/constitution/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789'],
      ['Vie publique : comment les droits sont protégés', 'https://www.vie-publique.fr/fiches/23868-comment-sont-proteges-les-droits-des-citoyens'],
    ],
  },
  {
    slug: 'histoire-geographie',
    title: 'Histoire et géographie : relier les dates, les droits et les territoires',
    shortTitle: 'Histoire, géographie et culture',
    description: 'Comprendre 1789, distinguer le droit de vote des femmes de son premier exercice et situer la France au-delà de la métropole.',
    objective: 'Associer un repère à son sens et éviter de confondre une date juridique, un événement et une localisation.',
    sections: [
      ['reperes', 'Une date doit raconter quelque chose', `<p>La Déclaration des droits de l’homme et du citoyen est adoptée en 1789, dans le contexte de la Révolution française. Elle affirme des principes de liberté et d’égalité qui restent des références fondamentales. Retenir seulement les quatre chiffres ne suffit pas : associez le document à ce qu’il change dans la manière de penser les droits et le pouvoir.</p><p>Notre méthode consiste à construire une petite fiche avec trois cases : date, événement, signification. Par exemple, « 1789 / Déclaration / affirmation de droits ». Cette structure permet de répondre à une question formulée dans l’autre sens : on peut vous demander le document, sa période ou le principe qu’il exprime.</p>`],
      ['vote', '1944 et 1945 ne répondent pas à la même question', `<p>Les Françaises obtiennent le droit de vote et d’éligibilité en 1944. Elles votent pour la première fois aux élections municipales de 1945. Les deux dates sont donc justes, mais pour deux événements différents. « Obtenir un droit » et « exercer ce droit pour la première fois » sont les mots décisifs.</p><p>Cette distinction explique une erreur fréquente dans un QCM : reconnaître une date connue et répondre avant de terminer l’énoncé. Soulignez mentalement le verbe. Le progrès de l’égalité politique se comprend aussi comme un processus : un droit peut être affirmé après des revendications puis mis en pratique lors d’une élection.</p>`],
      ['territoire', 'La France ne se limite pas à la métropole', `<p>La France comprend des territoires situés hors d’Europe. La Guyane se trouve en Amérique du Sud et La Réunion dans l’océan Indien. Les territoires ultramarins n’ont pas tous le même statut administratif. « Outre-mer » décrit un ensemble de territoires ; ce terme ne signifie pas « pays étranger ».</p><p>Pour apprendre une localisation, associez un territoire à un océan ou à un continent avant d’ajouter des détails administratifs. Évitez de déduire le statut d’un territoire de sa distance avec Paris. La Guyane et la Martinique disposent de collectivités territoriales uniques exerçant des compétences départementales et régionales : une carte géographique ne suffit pas à expliquer toute l’organisation politique.</p>`],
    ],
    questions: [
      ['Quelle date correspond à l’obtention du droit de vote par les Françaises ?', ['1789.', '1944.', '1945.', '1958.'], 1, ['1789 renvoie ici à la Déclaration des droits, pas à l’octroi du vote aux femmes.', 'Le droit est reconnu en 1944.', '1945 correspond à leur premier vote aux élections municipales.', '1958 est le repère de la Constitution de la Ve République.']],
      ['Quelle association est correcte ?', ['Guyane : Amérique du Sud.', 'La Réunion : Europe continentale.', 'Guyane : océan Indien.', 'Tous les territoires français sont en Europe.'], 0, ['Cette localisation rappelle la présence française hors du continent européen.', 'La Réunion se situe dans l’océan Indien.', 'L’océan Indien correspond ici à La Réunion, pas à la Guyane.', 'La France comprend aussi des territoires ultramarins.']],
      ['Comment réviser utilement la Déclaration de 1789 ?', ['Retenir seulement la couleur de sa couverture.', 'La confondre avec la première élection des femmes.', 'Associer la date, le document et les principes affirmés.', 'Supposer qu’elle concerne uniquement la géographie.'], 2, ['Un détail de présentation n’explique ni le document ni son rôle.', 'Il s’agit de deux repères historiques différents.', 'Cette association permet de reconnaître plusieurs formulations d’une question.', 'La Déclaration porte sur les droits et l’organisation politique.']],
    ],
    exercise: 'Faites une frise avec 1789, 1944, 1945 et 1958. Sous chaque date, écrivez une seule phrase. Puis cachez les dates et tentez de les retrouver à partir des phrases. Pour la géographie, placez la Guyane et La Réunion sur une carte du monde avant de revoir leurs noms.',
    sources: [
      ['Déclaration des droits de 1789', 'https://www.legifrance.gouv.fr/contenu/menu/droit-national-en-vigueur/constitution/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789'],
      ['Assemblée nationale : chronologie du vote des femmes', 'https://www2.assemblee-nationale.fr/decouvrir-l-assemblee/histoire/le-suffrage-universel/la-conquete-de-la-citoyennete-politique-des-femmes/chronologie-du-droit-de-vote-et-d-eligibilite-des-femmes'],
      ['Insee : départements, régions et collectivités d’outre-mer', 'https://www.insee.fr/fr/metadonnees/definition/c2316'],
      ['Vie publique : statut de la Guyane et de la Martinique', 'https://www.vie-publique.fr/fiches/20148-quel-est-le-statut-de-la-guyane-et-de-la-martinique'],
      ['Constitution du 4 octobre 1958', 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000571356/'],
    ],
  },
  {
    slug: 'vie-quotidienne',
    title: 'Vivre en France : école, services et réflexes face à une urgence',
    shortTitle: 'Vivre dans la société française',
    description: 'Distinguer instruction et scolarisation, reconnaître une urgence et préparer une démarche grâce à des situations commentées.',
    objective: 'Identifier le besoin dans une situation quotidienne et choisir une action adaptée, sans confondre urgence et démarche courante.',
    sections: [
      ['ecole', 'Instruction obligatoire et scolarisation', `<p>En France, l’instruction est obligatoire de 3 à 16 ans pour les enfants qui y résident, français ou étrangers. L’instruction désigne l’apprentissage auquel l’enfant doit accéder. La scolarisation est le fait de fréquenter un établissement. L’instruction en famille est soumise à autorisation et à des conditions : ce n’est pas une option libre sans démarche.</p><p>Cette différence de vocabulaire compte dans un QCM. Une réponse disant que l’apprentissage est facultatif avant 6 ans ne correspond pas à la règle actuelle. Une autre réponse affirmant que les parents peuvent simplement arrêter l’instruction à leur convenance ne convient pas non plus. Une obligation de formation existe également pour les jeunes de 16 à 18 ans ; elle ne doit pas être confondue avec la tranche d’âge de l’instruction obligatoire.</p>`],
      ['urgence', 'Savoir distinguer urgence et renseignement', `<p>Le 112 est un numéro d’urgence utilisable dans l’Union européenne. En France, le 15 correspond au Samu, le 17 à la police ou à la gendarmerie et le 18 aux pompiers. Les numéros d’urgence servent à une situation nécessitant une intervention, pas à connaître les horaires d’un guichet.</p><p>Dans un exercice, cherchez d’abord s’il existe un danger immédiat. Pour une urgence réelle, donnez une localisation précise, décrivez les faits et suivez les instructions de l’opérateur. Pour un rendez-vous administratif ou une question sur un document, recherchez plutôt le service compétent. La bonne réponse dépend du besoin décrit, et pas du numéro que vous connaissez le mieux.</p>`],
      ['demarches', 'Préparer une démarche plutôt que deviner', `<p>Les démarches liées à l’école, au travail, à la santé ou au logement peuvent demander des justificatifs différents. Un bon réflexe consiste à lire la liste du service concerné, à vérifier l’adresse du site et à conserver une copie de ce que l’on transmet. Un message reçu sur les réseaux sociaux ne suffit pas à établir une règle administrative.</p><p>Notre exercice pratique : vous devez préparer un rendez-vous dont le courrier mentionne trois pièces. Notez chaque pièce, son format et l’éventuelle date limite. Si une consigne est ambiguë, posez une question précise au service : « Quel document peut remplacer celui-ci ? » Cette méthode réduit les oublis sans prétendre qu’une liste unique conviendrait à toutes les situations.</p>`],
    ],
    questions: [
      ['Quelle tranche d’âge correspond à l’instruction obligatoire en France ?', ['De 6 à 12 ans.', 'De 3 à 16 ans.', 'Uniquement à partir de 18 ans.', 'Seulement pour les enfants français.'], 1, ['L’obligation commence avant 6 ans et se poursuit au-delà de 12 ans.', 'C’est la tranche d’âge de l’instruction obligatoire.', 'L’instruction obligatoire concerne l’enfance et l’adolescence.', 'La nationalité étrangère ne supprime pas cette obligation pour un enfant résidant en France.']],
      ['Quel besoin correspond à l’usage du 112 ?', ['Demander le prix d’un document.', 'Vérifier les horaires de la mairie.', 'Signaler une urgence nécessitant des secours.', 'Réserver une séance de révision.'], 2, ['Une information tarifaire relève du service concerné.', 'Les horaires sont un renseignement courant.', 'Le 112 permet de joindre les secours dans l’Union européenne.', 'Une réservation pédagogique n’est pas une urgence.']],
      ['Une consigne pour un dossier est ambiguë. Quel réflexe est utile ?', ['Inventer un justificatif.', 'Envoyer ses documents à tous les comptes qui proposent de l’aide.', 'Ignorer la date limite.', 'Vérifier la source officielle et demander une précision au service.'], 3, ['Une information inventée peut compromettre le dossier.', 'La diffusion non maîtrisée de documents personnels n’aide pas à vérifier une règle.', 'Une ambiguïté ne fait pas disparaître les échéances.', 'Une question ciblée au service compétent aide à obtenir une consigne adaptée.']],
    ],
    exercise: 'Classez trois situations : danger immédiat, renseignement courant, dossier à préparer. Pour chacune, écrivez le service à contacter et l’information à donner. Puis expliquez à voix haute pourquoi appeler les secours pour une formalité serait une mauvaise orientation.',
    sources: [
      ['Service Public : instruction obligatoire', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1898'],
      ['Service Public : numéros d’urgence', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F33954'],
      ['Ministère de l’Intérieur : fiches de formation civique', 'https://formation-civique.interieur.gouv.fr/fiches-par-thematiques/'],
    ],
  },
];
