import { mkdir, writeFile } from 'node:fs/promises';
import { courses, reviewedOn } from '../content/courses.mjs';

const output = new URL('../public/cours/', import.meta.url);
const escape = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const href = (course) => `/cours/${course.slug}.html`;
const cards = courses.map((course, i) => `<a href="${href(course)}"><span class="kicker">Cours ${i + 1}</span>${escape(course.shortTitle)}<span>${escape(course.description)}</span></a>`).join('\n');

function page(title, description, path, body, ads = true) {
  return `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(title)} | Test Civique QCM</title><meta name="description" content="${escape(description)}">
<link rel="canonical" href="https://prep-testcivique.fr${path}"><link rel="stylesheet" href="/site-pages.css?v=20260914">
${ads ? '<meta name="google-adsense-account" content="ca-pub-2101066490685216"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2101066490685216" crossorigin="anonymous"></script>' : ''}
</head><body><a class="skip-link" href="#contenu">Aller au contenu</a>
<header class="public-header"><nav class="public-nav" aria-label="Navigation principale"><a class="public-logo" href="/"><span>TC</span><strong>Test Civique QCM</strong></a><div class="public-links"><a href="/cours/">Les cours</a><a href="/guides/examen-civique-2026.html">L’examen</a><a href="/guides/plan-revision.html">Méthode</a><a href="/about.html">À propos</a></div><a class="public-action" href="/app.html">S’entraîner</a></nav></header>
<main class="article-main" id="contenu">${body}</main>
<footer class="public-footer"><div class="footer-inner"><div><strong>Test Civique QCM</strong><p>Une préparation gratuite et indépendante. Ces cours ne constituent ni une attestation ni un conseil sur votre dossier personnel.</p></div><nav aria-label="Ressources"><strong>Apprendre</strong><a href="/cours/">Les cinq cours</a><a href="/guides/plan-revision.html">Plan de révision</a><a href="/app.html">Quiz gratuits</a></nav><nav aria-label="Informations"><strong>Informations</strong><a href="/about.html">Méthode éditoriale</a><a href="/privacy-policy.html">Confidentialité</a></nav></div><p class="footer-legal">Site non officiel, sans affiliation avec l’administration française.</p></footer></body></html>\n`;
}

await mkdir(output, { recursive: true });
for (const [index, course] of courses.entries()) {
  const toc = course.sections.map(([id, title]) => `<a href="#${id}">${escape(title)}</a>`).join('');
  const sections = course.sections.map(([id, title, body]) => `<section aria-labelledby="${id}"><h2 id="${id}">${escape(title)}</h2>${body}</section>`).join('\n');
  const questions = course.questions.map(([prompt, options, answer, explanations], i) => {
    if (options.length !== 4 || explanations.length !== 4 || answer < 0 || answer > 3) throw new Error(`Invalid question in ${course.slug}`);
    return `<section class="worked-question" aria-labelledby="question-${i + 1}"><h3 id="question-${i + 1}">${i + 1}. ${escape(prompt)}</h3><ol type="A">${options.map((option) => `<li>${escape(option)}</li>`).join('')}</ol><div class="answer-explanation"><h4>Correction : réponse ${String.fromCharCode(65 + answer)}</h4><ul>${explanations.map((explanation, choice) => `<li><strong>${String.fromCharCode(65 + choice)} ${choice === answer ? '(correct)' : '(incorrect)'}.</strong> ${escape(explanation)}</li>`).join('')}</ul></div></section>`;
  }).join('\n');
  const sources = course.sources.map(([label, url]) => `<li><a href="${escape(url)}">${escape(label)}</a></li>`).join('');
  const next = courses[(index + 1) % courses.length];
  const body = `<header class="article-heading"><p class="kicker">Cours ${index + 1} / 5 · Lecture et exercices</p><h1>${escape(course.title)}</h1><p class="intro">${escape(course.description)}</p><p class="article-meta">Rédaction : Test Civique QCM · Mis à jour le <time datetime="${reviewedOn}">14 septembre 2026</time></p></header>
<div class="article-layout"><article class="article-content"><div class="notice"><strong>Objectif de cette leçon :</strong> ${escape(course.objective)}</div>${sections}
<section aria-labelledby="exercices"><h2 id="exercices">Trois exercices, toutes les réponses expliquées</h2><p>Ces situations et propositions ont été rédigées pour apprendre. Elles ne sont pas des questions officielles reproduites et ne prédisent pas le sujet de l’examen. Choisissez une réponse avant de lire la correction ; expliquez ensuite pourquoi les trois autres ne conviennent pas.</p>${questions}</section>
<section aria-labelledby="pratique"><h2 id="pratique">Passer de la lecture à la compréhension</h2><p>${escape(course.exercise)}</p><p>Notez l’erreur avec vos propres mots. Reprenez l’exercice le lendemain sans regarder la correction : reconnaître une réponse juste à la lecture est plus facile que retrouver seul son raisonnement.</p></section>
<p>Vous avez terminé les exercices ? Notre <a href="/guides/analyser-resultats.html">guide pour analyser les résultats</a> aide à distinguer une notion inconnue, une confusion et une erreur de lecture. Il propose une fiche imprimable pour préparer la prochaine séance.</p>
<section aria-labelledby="sources"><h2 id="sources">Sources et limites de la fiche</h2><p>Les références suivantes permettent de vérifier les notions. Les exemples et la méthode de révision sont des créations pédagogiques du site. Cette leçon couvre des repères du thème, pas l’intégralité des connaissances de chaque mention de l’examen.</p><ul class="source-list">${sources}</ul><p><a href="/about.html#corrections">Signaler une erreur ou une source qui a changé</a></p></section></article>
<aside class="article-aside" aria-label="Sommaire"><strong>Dans cette leçon</strong>${toc}<a href="#exercices">Exercices corrigés</a><a href="#pratique">À faire soi-même</a><a href="#sources">Sources</a><p><a href="/cours/">Revenir aux cinq cours</a></p></aside></div>
<section class="related-band"><h2>Continuer à apprendre</h2><div class="related-grid"><a href="${href(next)}">${escape(next.shortTitle)}<span>Lire une autre leçon et ses corrections.</span></a><a href="/guides/plan-revision.html">Organiser les révisions<span>Alterner lecture, rappel et simulation.</span></a><a href="/app.html">S’évaluer avec le quiz<span>Choisir la mention de votre démarche.</span></a></div></section>`;
  await writeFile(new URL(`${course.slug}.html`, output), page(course.title, course.description, href(course), body));
}

await writeFile(new URL('index.html', output), page('Cours gratuits et exercices corrigés pour l’examen civique', 'Cinq leçons pour comprendre les thèmes de l’examen civique, avec quinze exercices et une explication de chaque réponse.', '/cours/', `<header class="article-heading"><p class="kicker">Comprendre avant de mémoriser</p><h1>Cinq thèmes, des repères concrets.</h1><p class="intro">Les cours expliquent les notions ; les exercices vous apprennent à les appliquer. Chaque leçon est gratuite et lisible sans compte.</p></header><div class="article-content"><h2>Comment utiliser ces leçons</h2><p>Commencez par le thème où vous hésitez le plus. Lisez les explications puis répondez aux trois questions sur une feuille avant de consulter les corrections. Pour chaque erreur, cherchez si vous avez confondu un mot, une fonction ou une date. La correction de chaque mauvaise proposition sert à identifier précisément cette confusion.</p><p>Ces cours donnent un socle de compréhension pour les parcours carte de séjour pluriannuelle, carte de résident et naturalisation. Ils ne remplacent pas les listes de connaissances propres à chaque mention : utilisez votre guide de parcours pour choisir la bonne liste. Les exercices sont des créations pédagogiques, pas une reproduction du questionnaire officiel.</p></div><div class="related-grid course-grid">${cards}</div><section class="article-content"><h2>Un exemple de révision active</h2><p>Si vous confondez 1944 et 1945, relisez le passage historique puis écrivez deux phrases : une sur l’obtention du droit de vote des femmes, l’autre sur leur premier vote. Changez ensuite le sens de la question : partez de l’événement pour retrouver la date. Vous travaillez ainsi la distinction qui pose problème, au lieu de répéter au hasard une série complète.</p><h2>Choisir sa démarche</h2><ul><li><a href="/guides/carte-sejour-pluriannuelle.html">Carte de séjour pluriannuelle : construire les premiers repères</a></li><li><a href="/guides/carte-resident.html">Carte de résident : consolider les notions et les distinctions</a></li><li><a href="/guides/naturalisation.html">Naturalisation : relier droits, histoire et institutions</a></li></ul><p>Les sources sont données à la fin de chaque cours. Pour comprendre la rédaction des exemples et les limites du service, consultez notre <a href="/about.html">méthode éditoriale</a>.</p></section>`, false));
console.log(`Generated ${courses.length} static lessons and their index.`);
